### ISSUE TITLE
Tray app fails with "File Not Found" error when run outside of the build folder

### ISSUE THREAD

**Issue by asvw** [momentumai-team/cloud-provider-kind-tray#1]
The tray app fails to start when executed from a directory other than where it was built, with the error:

open assets/load-balancer.png: no such file or directory
panic: runtime error: index out of range [0] with length 0

Reproduce:
1. Build the app using make build, install using make install
2. Change the working dir to a different location.
3. Run cloud-provider-kind-tray

Expected Behavior:
The app should start successfully from any folder.

Environment:
MacOS: 14.2
Go: go1.22.4 darwin/amd64

**Comment by calebwashburn** [comment]
Fixed.  Thanks @asvw for pointing out issue!
